### ISSUE TITLE
Qeydlər 

### ISSUE THREAD

**Issue by samirkarimov** [feridkerim/PragmatechFoundationProject#1]
- Layihənin işlənilməsini bəyəndim. Sistemli yazmısan
- grid sistemi tetbiq olunmayıb. O tetbiq olunmuş olsaydı çox daha sistemli olmuş olardı
- layihə başdan analiz olunub hansı kodlar ortaq classlar şəklində yazılması üçün plan hazırlanıb tətbiq olunmalıdır

Ümümi dəyərləndirmə 8/10-dur

**Comment by feridkerim** [comment]
fix olundu
