### ISSUE TITLE
Adlandirma problemi

### ISSUE THREAD

**Issue by samirkarimov** [feridkerim/PragmatechFoundationProject#2]
https://github.com/feridkerim/PragmatechFoundationProject/blob/628568010b41d426818da8e63860a07dc4e62357/index.html#L46

umumi adlandirma stilini bir az deyissen ela olar.logomenyu yerine logo-menyu  ya da logo_menyu yazsan ela olar. eger bir class adinda iki soz istifade edeceksense onu mutleg necese bir birinden ayir ki oxunaqli olsun

**Comment by feridkerim** [comment]
fix olundu
