### ISSUE TITLE
SASS-la bagli meslehetler

### ISSUE THREAD

**Issue by samirkarimov** [feridkerim/PragmatechFoundationProject#3]
- Mumkun mertebe variable mentiginden istifade etmeye calis isin suretlener
- 2 ya da daha cox tekrarlanan deyerleri meselen 40px kimi onlari variable halina getir
- 2 ya da daha cox tekrarlanan propertyleri meselen display:flex kimi onlari ya ortaq class halina getir ya da extendle basga yerde yaz hazir saxla ki daimi istifade edebilesen vaxt gazanasan

**Comment by feridkerim** [comment]
display flex meselesi fix olundu, tekrarlanan deyerleri fix edirem
