### ISSUE TITLE
Cart

### ISSUE THREAD

**Issue by samirkarimov** [feridkerim/PragmatechFoundationProject#4]
- [ ] ![Screenshot_1](https://user-images.githubusercontent.com/24611841/103488330-10f23f80-4e25-11eb-82ea-047b0e080224.jpg)
Mehsul sayinin artmasi giymete ve umumi meblege tesir etmir bunu fix etmek lazimdir

**Comment by feridkerim** [comment]
fix olundu

**Comment by samirkarimov** [comment]
good
