### ISSUE TITLE
Dropdown menu 

### ISSUE THREAD

**Issue by samirkarimov** [feridkerim/PragmatechFoundationProject#5]
![Screenshot_2](https://user-images.githubusercontent.com/24611841/103488369-5c0c5280-4e25-11eb-9c32-3b19f5265e97.jpg)
ara mesafe olmamalidir submenude

**Comment by feridkerim** [comment]
fix olundu. menin brauzerimde ara mesafaesi olmurdu ona gore gormemisem.

**Comment by samirkarimov** [comment]
good thankss
