### ISSUE TITLE
Bitirilmeli olan sehifeler

### ISSUE THREAD

**Issue by samirkarimov** [feridkerim/PragmatechFoundationProject#6]
- [ ] Mehsul kategoriyasi
- [ ] Mehsul sehifesi
- [ ] Qeydiyyat ve login sehifeleri
- [ ] Sifaris sehifeleri

bunlarin bitmesi ucun 5-ci gun axsama geder vaxtin var Ferid

**Comment by feridkerim** [comment]
fix olundu

**Comment by samirkarimov** [comment]
tesekkur
